-- Generated by nwg-displays on 2026-08-31 at 17:30:52. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@59.95",
    position = "5120x0",
    scale = 1.0,
    transform = 3
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@59.95",
    position = "6560x0",
    scale = 1
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "2560x1440@59.95",
    position = "9120x0",
    scale = 1,
    bitdepth = 10
})
