-- Generated by nwg-displays on 2026-09-29 at 15:54:53. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "2560x1440@74.97",
    position = "2424x2733",
    scale = 1.0,
    vrr = 0,
    transform = 1
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@60.0",
    position = "6424x2733",
    scale = 1,
    vrr = 0,
    transform = 1
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@74.97",
    position = "3864x2733",
    scale = 1,
    vrr = 0
})
