## name: Ayu Dark
## dark: true
## background: #0A0E14

foreground              #B3B1AD
background              #0A0E14
selection_foreground    #B3B1AD
selection_background    #273747

cursor                  #E6B450
cursor_text_color       #0A0E14

url_color               #39BAE6

active_border_color     #39BAE6
inactive_border_color   #1F2430
bell_border_color       #FF8F40

active_tab_foreground   #0A0E14
active_tab_background   #39BAE6
inactive_tab_foreground #B3B1AD
inactive_tab_background #1F2430
tab_bar_background      #0D1017

color0  #1F2430
color8  #686868
color1  #FF3333
color9  #FF3333
color2  #91B362
color10 #91B362
color3  #F9AF4F
color11 #E6B450
color4  #53BDFA
color12 #53BDFA
color5  #FAE994
color13 #FAE994
color6  #90E1C6
color14 #90E1C6
color7  #C7C7C7
color15 #FFFFFF
