## name: Ayu Light
## dark: false
## background: #FAFAFA

foreground              #5C6166
background              #FAFAFA
selection_foreground    #FAFAFA
selection_background    #C9D0D8

cursor                  #FF9940
cursor_text_color       #FAFAFA

url_color               #399EE6

active_border_color     #399EE6
inactive_border_color   #C9D0D8
bell_border_color       #FA8D3E

active_tab_foreground   #FAFAFA
active_tab_background   #399EE6
inactive_tab_foreground #5C6166
inactive_tab_background #E7EAF0
tab_bar_background      #E7EAF0

color0  #5C6166
color8  #8A9199
color1  #EA3D54
color9  #EA3D54
color2  #86B300
color10 #86B300
color3  #F2AE49
color11 #F2AE49
color4  #36A3D9
color12 #36A3D9
color5  #A37ACC
color13 #A37ACC
color6  #4CBF99
color14 #4CBF99
color7  #CBCDD2
color15 #FFFFFF
