## name: Everforest Light
## dark: false
## background: #FDF6E3

foreground              #5C6A72
background              #FDF6E3
selection_foreground    #5C6A72
selection_background    #C9D0C8

cursor                  #5C6A72
cursor_text_color       #FDF6E3

url_color               #3A94C5

active_border_color     #8DA101
inactive_border_color   #C9D0C8
bell_border_color       #F57D26

active_tab_foreground   #FDF6E3
active_tab_background   #8DA101
inactive_tab_foreground #5C6A72
inactive_tab_background #E5DFC5
tab_bar_background      #EDE8D0

color0  #E5DFC5
color8  #A6B0A0
color1  #F85552
color9  #F85552
color2  #8DA101
color10 #8DA101
color3  #DFA000
color11 #DFA000
color4  #3A94C5
color12 #3A94C5
color5  #DF69BA
color13 #DF69BA
color6  #35A77C
color14 #35A77C
color7  #5C6A72
color15 #272E33
