## name: GitHub Light
## dark: false
## background: #FFFFFF

foreground              #24292F
background              #FFFFFF
selection_foreground    #FFFFFF
selection_background    #0550AE

cursor                  #24292F
cursor_text_color       #FFFFFF

url_color               #0550AE

active_border_color     #0550AE
inactive_border_color   #D0D7DE
bell_border_color       #CF222E

active_tab_foreground   #FFFFFF
active_tab_background   #0550AE
inactive_tab_foreground #24292F
inactive_tab_background #F6F8FA
tab_bar_background      #F6F8FA

color0  #24292F
color8  #57606A
color1  #CF222E
color9  #A40E26
color2  #116329
color10 #1A7F37
color3  #633C01
color11 #953800
color4  #0550AE
color12 #218BFF
color5  #8250DF
color13 #A475F9
color6  #1B7C83
color14 #3192AA
color7  #6E7781
color15 #8C959F
