## name: Gruvbox Dark
## dark: true
## background: #282828

foreground              #EBDBB2
background              #282828
selection_foreground    #282828
selection_background    #D65D0E

cursor                  #EBDBB2
cursor_text_color       #282828

url_color               #D65D0E

active_border_color     #D79921
inactive_border_color   #3C3836
bell_border_color       #FB4934

active_tab_foreground   #282828
active_tab_background   #D79921
inactive_tab_foreground #EBDBB2
inactive_tab_background #3C3836
tab_bar_background      #1D2021

color0  #282828
color8  #928374
color1  #CC241D
color9  #FB4934
color2  #98971A
color10 #B8BB26
color3  #D79921
color11 #FABD2F
color4  #458588
color12 #83A598
color5  #B16286
color13 #D3869B
color6  #689D6A
color14 #8EC07C
color7  #A89984
color15 #EBDBB2
