color0 #11112d
color1 #fd4663
color2 #9bfece
color3 #fff59b
color4 #a9aefe
color5 #fd4663
color6 #9bfece
color7 #f3edf7
color8 #21215f
color9 #fd4663
color10 #9bfece
color11 #fff59b
color12 #a9aefe
color13 #fd4663
color14 #9bfece
color15 #ffffff

cursor                #fff59b
cursor_text_color     #070722
background            #070722
foreground            #f3edf7
selection_foreground  #070722
selection_background  #f3edf7
active_border_color   #fff59b
inactive_border_color #11112d
url_color             #fff59b

active_tab_foreground   #0e0e43
active_tab_background   #fff59b
inactive_tab_foreground #7c80b4
inactive_tab_background #11112d
cursor_trail_color      #7c80b4
