## name: Nord
## dark: true
## background: #2E3440

foreground              #D8DEE9
background              #2E3440
selection_foreground    #D8DEE9
selection_background    #4C566A

cursor                  #D8DEE9
cursor_text_color       #2E3440

url_color               #88C0D0

active_border_color     #88C0D0
inactive_border_color   #4C566A
bell_border_color       #EBCB8B

active_tab_foreground   #2E3440
active_tab_background   #88C0D0
inactive_tab_foreground #D8DEE9
inactive_tab_background #3B4252
tab_bar_background      #2E3440

color0  #3B4252
color8  #4C566A
color1  #BF616A
color9  #BF616A
color2  #A3BE8C
color10 #A3BE8C
color3  #EBCB8B
color11 #EBCB8B
color4  #81A1C1
color12 #81A1C1
color5  #B48EAD
color13 #B48EAD
color6  #88C0D0
color14 #8FBCBB
color7  #E5E9F0
color15 #ECEFF4
