## name: Papercolor Light
## dark: false
## background: #EEEEEE

foreground              #444444
background              #EEEEEE
selection_foreground    #EEEEEE
selection_background    #0087AF

cursor                  #444444
cursor_text_color       #EEEEEE

url_color               #0087AF

active_border_color     #0087AF
inactive_border_color   #BCBCBC
bell_border_color       #D70000

active_tab_foreground   #EEEEEE
active_tab_background   #0087AF
inactive_tab_foreground #444444
inactive_tab_background #BCBCBC
tab_bar_background      #BCBCBC

color0  #EEEEEE
color8  #BCBCBC
color1  #AF0000
color9  #D70000
color2  #008700
color10 #005F00
color3  #5F8700
color11 #878700
color4  #0087AF
color12 #005F87
color5  #878787
color13 #875F87
color6  #005F87
color14 #0087AF
color7  #444444
color15 #444444
