## name: Rose Pine Moon
## dark: true
## background: #232136

foreground              #E0DEF4
background              #232136
selection_foreground    #E0DEF4
selection_background    #44415A

cursor                  #E0DEF4
cursor_text_color       #232136

url_color               #3E8FB0

active_border_color     #3E8FB0
inactive_border_color   #6E6A86
bell_border_color       #F6C177

active_tab_foreground   #232136
active_tab_background   #3E8FB0
inactive_tab_foreground #E0DEF4
inactive_tab_background #2A2740
tab_bar_background      #1A1826

color0  #2A2740
color8  #6E6A86
color1  #EB6F92
color9  #EB6F92
color2  #3E8FB0
color10 #3E8FB0
color3  #F6C177
color11 #F6C177
color4  #9CCFD8
color12 #9CCFD8
color5  #C4A7E7
color13 #C4A7E7
color6  #EA9A97
color14 #EA9A97
color7  #E0DEF4
color15 #E0DEF4
