## name: Rose Pine Dawn
## dark: false
## background: #FAF4ED

foreground              #575279
background              #FAF4ED
selection_foreground    #575279
selection_background    #F2E9E1

cursor                  #9893A5
cursor_text_color       #FAF4ED

url_color               #286983

active_border_color     #56949F
inactive_border_color   #D7827E
bell_border_color       #EA9D34

active_tab_foreground   #FAF4ED
active_tab_background   #56949F
inactive_tab_foreground #575279
inactive_tab_background #F2E9E1
tab_bar_background      #EFF1F5

color0  #F2E9E1
color8  #9893A5
color1  #B4637A
color9  #B4637A
color2  #286983
color10 #286983
color3  #EA9D34
color11 #EA9D34
color4  #56949F
color12 #56949F
color5  #907AA9
color13 #907AA9
color6  #D7827E
color14 #D7827E
color7  #575279
color15 #26233A
