## name: Solarized Light
## dark: false
## background: #FDF6E3

foreground              #657B83
background              #FDF6E3
selection_foreground    #FDF6E3
selection_background    #073642

cursor                  #657B83
cursor_text_color       #FDF6E3

url_color               #268BD2

active_border_color     #268BD2
inactive_border_color   #93A1A1
bell_border_color       #CB4B16

active_tab_foreground   #FDF6E3
active_tab_background   #268BD2
inactive_tab_foreground #657B83
inactive_tab_background #EEE8D5
tab_bar_background      #EEE8D5

color0  #073642
color8  #002B36
color1  #DC322F
color9  #CB4B16
color2  #859900
color10 #586E75
color3  #B58900
color11 #657B83
color4  #268BD2
color12 #839496
color5  #D33682
color13 #6C71C4
color6  #2AA198
color14 #93A1A1
color7  #EEE8D5
color15 #FDF6E3
