## name: Tokyo Night
## dark: true
## background: #1A1B26

foreground              #C0CAF5
background              #1A1B26
selection_foreground    #C0CAF5
selection_background    #364A82

cursor                  #C0CAF5
cursor_text_color       #1A1B26

url_color               #73DACA

active_border_color     #7AA2F7
inactive_border_color   #3B4261
bell_border_color       #E0AF68

active_tab_foreground   #1A1B26
active_tab_background   #7AA2F7
inactive_tab_foreground #787C99
inactive_tab_background #1F2335
tab_bar_background      #15161E

color0  #15161E
color8  #414868
color1  #F7768E
color9  #F7768E
color2  #9ECE6A
color10 #9ECE6A
color3  #E0AF68
color11 #E0AF68
color4  #7AA2F7
color12 #7AA2F7
color5  #BB9AF7
color13 #BB9AF7
color6  #7DCFFF
color14 #7DCFFF
color7  #A9B1D6
color15 #C0CAF5
